spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/marketing_vk
      username: root
      password: pass
      connectionProperties: useUnicode=true;characterEncoding=utf-8;
   jpa:
      generate-ddl: true
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            temp:
               use_jdbc_metadata_defaults: false
   liquibase:
      change-log: classpath:db/liquibase-changelog.xml
      parameters:
         default-schema-prefix: ${spring.liquibase.default-schema}