spring:
   datasource:
      url: ${DB_CONNECT}/${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
   jpa:
      generate-ddl: false
      hibernate:
         ddl-auto: none
      properties:
         hibernate:
            temp:
               use_jdbc_metadata_defaults: false
   liquibase:
      change-log: classpath:db/liquibase-changelog.xml
      parameters:
         default-schema-prefix: ${spring.liquibase.default-schema}