spring:
   datasource:
      url: jdbc:mysql://127.0.0.1/marketing_vk
      username: root
      password: pass
      connectionProperties: useUnicode=true;characterEncoding=utf-8;
   jpa:
      properties:
         hibernate:
            default_schema: fpm_product
            format_sql: true
   liquibase:
      change-log: classpath:db/liquibase-changelog-local.xml

logging:
   level:
      org.hibernate: debug
      org.hibernate.SQL: debug
      org.hibernate.type: trace
      org.hibernate.type.descriptor.sql: trace
      org.springframework: debug
      org.zalando.logbook.Logbook: trace
      ru.x5.omni.messaging.aop.MessageLogging: trace
   pattern:
      console: '%date  %clr(%-5level) --- [%12.12thread] %cyan(%-40.40logger{40}) : %msg %n'